name: Deploy files to HRIS API Prod
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive  # Fetch submodules

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.20'

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer

      - name: Install composer dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
